"""Add processed_for_water field to Payment model

Revision ID: 276e6c3abc96
Revises: 3322e6ce7ae0
Create Date: 2025-03-20 17:03:31.157228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276e6c3abc96'
down_revision = '3322e6ce7ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_for_water', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('processed_for_water')

    # ### end Alembic commands ###
