"""Add pushover_key to User model

Revision ID: 3322e6ce7ae0
Revises: 3c8282700106
Create Date: 2025-03-19 14:19:02.829598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3322e6ce7ae0'
down_revision = '3c8282700106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pushover_key', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pushover_key')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
