"""Add acknowledged column to WaterUsage model

Revision ID: 3ed7b6d87f57
Revises: d7e33de9cef7
Create Date: 2025-04-03 02:56:16.480891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed7b6d87f57'
down_revision = 'd7e33de9cef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acknowledged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.drop_column('acknowledged')

    # ### end Alembic commands ###
