"""Add WaterBalance model v2

Revision ID: 5d59347f120a
Revises: 7892fe618a7b
Create Date: 2025-04-02 07:19:57.475800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d59347f120a'
down_revision = '7892fe618a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_balance', schema=None) as batch_op:
        batch_op.alter_column('cubic_meters',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_balance', schema=None) as batch_op:
        batch_op.alter_column('cubic_meters',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
