"""Initial migration

Revision ID: 7892fe618a7b
Revises: 9f4c16acfee2
Create Date: 2025-03-31 09:56:55.052029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7892fe618a7b'
down_revision = '9f4c16acfee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cubic_meters', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_balance')
    # ### end Alembic commands ###
