"""Add transaction_ref to Payment model

Revision ID: d9df74f77b9b
Revises: fb5b84d04862
Create Date: 2025-03-12 05:42:06.207691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9df74f77b9b'
down_revision = 'fb5b84d04862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_ref', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['transaction_ref'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('transaction_ref')

    # ### end Alembic commands ###
