"""Add counter_id to WaterUsage

Revision ID: e7bac7d66db3
Revises: d9df74f77b9b
Create Date: 2025-03-12 16:47:50.426345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7bac7d66db3'
down_revision = 'd9df74f77b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counter_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('water_usage_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'counter', ['counter_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('water_usage_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.drop_column('counter_id')

    # ### end Alembic commands ###
